/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.public_;


import javax.annotation.Generated;

import ru.sevsu.db.public_.tables.MyCourses;
import ru.sevsu.db.public_.tables.Table;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.my_courses</code>.
     */
    public static final MyCourses MY_COURSES = ru.sevsu.db.public_.tables.MyCourses.MY_COURSES;

    /**
     * The table <code>public.table</code>.
     */
    public static final Table TABLE = ru.sevsu.db.public_.tables.Table.TABLE;
}
