/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudCourseLink implements Serializable {

    private static final long serialVersionUID = 650454294;

    private Integer sclId;
    private Integer studNum;
    private Integer courseNum;

    public StudCourseLink() {}

    public StudCourseLink(StudCourseLink value) {
        this.sclId = value.sclId;
        this.studNum = value.studNum;
        this.courseNum = value.courseNum;
    }

    public StudCourseLink(
        Integer sclId,
        Integer studNum,
        Integer courseNum
    ) {
        this.sclId = sclId;
        this.studNum = studNum;
        this.courseNum = courseNum;
    }

    public Integer getSclId() {
        return this.sclId;
    }

    public void setSclId(Integer sclId) {
        this.sclId = sclId;
    }

    public Integer getStudNum() {
        return this.studNum;
    }

    public void setStudNum(Integer studNum) {
        this.studNum = studNum;
    }

    public Integer getCourseNum() {
        return this.courseNum;
    }

    public void setCourseNum(Integer courseNum) {
        this.courseNum = courseNum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StudCourseLink (");

        sb.append(sclId);
        sb.append(", ").append(studNum);
        sb.append(", ").append(courseNum);

        sb.append(")");
        return sb.toString();
    }
}
