/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = -1841614213;

    private Long       id;
    private String     fio;
    private Short      grpNum;
    private BigDecimal grants;
    private Integer    profNum;

    public Student() {}

    public Student(Student value) {
        this.id = value.id;
        this.fio = value.fio;
        this.grpNum = value.grpNum;
        this.grants = value.grants;
        this.profNum = value.profNum;
    }

    public Student(
        Long       id,
        String     fio,
        Short      grpNum,
        BigDecimal grants,
        Integer    profNum
    ) {
        this.id = id;
        this.fio = fio;
        this.grpNum = grpNum;
        this.grants = grants;
        this.profNum = profNum;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFio() {
        return this.fio;
    }

    public void setFio(String fio) {
        this.fio = fio;
    }

    public Short getGrpNum() {
        return this.grpNum;
    }

    public void setGrpNum(Short grpNum) {
        this.grpNum = grpNum;
    }

    public BigDecimal getGrants() {
        return this.grants;
    }

    public void setGrants(BigDecimal grants) {
        this.grants = grants;
    }

    public Integer getProfNum() {
        return this.profNum;
    }

    public void setProfNum(Integer profNum) {
        this.profNum = profNum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(id);
        sb.append(", ").append(fio);
        sb.append(", ").append(grpNum);
        sb.append(", ").append(grants);
        sb.append(", ").append(profNum);

        sb.append(")");
        return sb.toString();
    }
}
