/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Teacher implements Serializable {

    private static final long serialVersionUID = 1406409878;

    private Integer teacherNum;
    private String  teacherFio;

    public Teacher() {}

    public Teacher(Teacher value) {
        this.teacherNum = value.teacherNum;
        this.teacherFio = value.teacherFio;
    }

    public Teacher(
        Integer teacherNum,
        String  teacherFio
    ) {
        this.teacherNum = teacherNum;
        this.teacherFio = teacherFio;
    }

    public Integer getTeacherNum() {
        return this.teacherNum;
    }

    public void setTeacherNum(Integer teacherNum) {
        this.teacherNum = teacherNum;
    }

    public String getTeacherFio() {
        return this.teacherFio;
    }

    public void setTeacherFio(String teacherFio) {
        this.teacherFio = teacherFio;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Teacher (");

        sb.append(teacherNum);
        sb.append(", ").append(teacherFio);

        sb.append(")");
        return sb.toString();
    }
}
