/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.sevsu.db.tables.Student;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record6<Integer, String, Integer, BigDecimal, Integer, Integer> {

    private static final long serialVersionUID = -1642575557;

    /**
     * Setter for <code>db.student.stud_num</code>.
     */
    public void setStudNum(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.student.stud_num</code>.
     */
    public Integer getStudNum() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.student.fio</code>.
     */
    public void setFio(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.student.fio</code>.
     */
    public String getFio() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db.student.grpnum</code>.
     */
    public void setGrpnum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.student.grpnum</code>.
     */
    public Integer getGrpnum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db.student.grants</code>.
     */
    public void setGrants(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.student.grants</code>.
     */
    public BigDecimal getGrants() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>db.student.profnum</code>.
     */
    public void setProfnum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>db.student.profnum</code>.
     */
    public Integer getProfnum() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>db.student.zachnum</code>.
     */
    public void setZachnum(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>db.student.zachnum</code>.
     */
    public Integer getZachnum() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, BigDecimal, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, BigDecimal, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Student.STUDENT.STUD_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Student.STUDENT.FIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Student.STUDENT.GRPNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Student.STUDENT.GRANTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Student.STUDENT.PROFNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Student.STUDENT.ZACHNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getStudNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getGrpnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getGrants();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getProfnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getZachnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStudNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGrpnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getGrants();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getProfnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getZachnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value1(Integer value) {
        setStudNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value2(String value) {
        setFio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value3(Integer value) {
        setGrpnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value4(BigDecimal value) {
        setGrants(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value5(Integer value) {
        setProfnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value6(Integer value) {
        setZachnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord values(Integer value1, String value2, Integer value3, BigDecimal value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Integer studNum, String fio, Integer grpnum, BigDecimal grants, Integer profnum, Integer zachnum) {
        super(Student.STUDENT);

        set(0, studNum);
        set(1, fio);
        set(2, grpnum);
        set(3, grants);
        set(4, profnum);
        set(5, zachnum);
    }
}
