/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.sevsu.db.tables.StudCourseLink;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudCourseLinkRecord extends UpdatableRecordImpl<StudCourseLinkRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -899206608;

    /**
     * Setter for <code>db.stud_course_link.scl_id</code>.
     */
    public void setSclId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.stud_course_link.scl_id</code>.
     */
    public Integer getSclId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.stud_course_link.stud_num</code>.
     */
    public void setStudNum(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.stud_course_link.stud_num</code>.
     */
    public Integer getStudNum() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db.stud_course_link.course_num</code>.
     */
    public void setCourseNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.stud_course_link.course_num</code>.
     */
    public Integer getCourseNum() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StudCourseLink.STUD_COURSE_LINK.SCL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return StudCourseLink.STUD_COURSE_LINK.STUD_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return StudCourseLink.STUD_COURSE_LINK.COURSE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSclId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getStudNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCourseNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSclId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStudNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCourseNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudCourseLinkRecord value1(Integer value) {
        setSclId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudCourseLinkRecord value2(Integer value) {
        setStudNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudCourseLinkRecord value3(Integer value) {
        setCourseNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudCourseLinkRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudCourseLinkRecord
     */
    public StudCourseLinkRecord() {
        super(StudCourseLink.STUD_COURSE_LINK);
    }

    /**
     * Create a detached, initialised StudCourseLinkRecord
     */
    public StudCourseLinkRecord(Integer sclId, Integer studNum, Integer courseNum) {
        super(StudCourseLink.STUD_COURSE_LINK);

        set(0, sclId);
        set(1, studNum);
        set(2, courseNum);
    }
}
