/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exercise implements Serializable {

    private static final long serialVersionUID = 741517799;

    private Integer exId;
    private Date    exDate;
    private Integer exClassRoom;
    private Integer courseNum;
    private String  exType;

    public Exercise() {}

    public Exercise(Exercise value) {
        this.exId = value.exId;
        this.exDate = value.exDate;
        this.exClassRoom = value.exClassRoom;
        this.courseNum = value.courseNum;
        this.exType = value.exType;
    }

    public Exercise(
        Integer exId,
        Date    exDate,
        Integer exClassRoom,
        Integer courseNum,
        String  exType
    ) {
        this.exId = exId;
        this.exDate = exDate;
        this.exClassRoom = exClassRoom;
        this.courseNum = courseNum;
        this.exType = exType;
    }

    public Integer getExId() {
        return this.exId;
    }

    public void setExId(Integer exId) {
        this.exId = exId;
    }

    public Date getExDate() {
        return this.exDate;
    }

    public void setExDate(Date exDate) {
        this.exDate = exDate;
    }

    public Integer getExClassRoom() {
        return this.exClassRoom;
    }

    public void setExClassRoom(Integer exClassRoom) {
        this.exClassRoom = exClassRoom;
    }

    public Integer getCourseNum() {
        return this.courseNum;
    }

    public void setCourseNum(Integer courseNum) {
        this.courseNum = courseNum;
    }

    public String getExType() {
        return this.exType;
    }

    public void setExType(String exType) {
        this.exType = exType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Exercise (");

        sb.append(exId);
        sb.append(", ").append(exDate);
        sb.append(", ").append(exClassRoom);
        sb.append(", ").append(courseNum);
        sb.append(", ").append(exType);

        sb.append(")");
        return sb.toString();
    }
}
