/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = -1272049716;

    private Integer    studNum;
    private String     fio;
    private Integer    grpnum;
    private BigDecimal grants;
    private Integer    profnum;
    private Integer    zachnum;

    public Student() {}

    public Student(Student value) {
        this.studNum = value.studNum;
        this.fio = value.fio;
        this.grpnum = value.grpnum;
        this.grants = value.grants;
        this.profnum = value.profnum;
        this.zachnum = value.zachnum;
    }

    public Student(
        Integer    studNum,
        String     fio,
        Integer    grpnum,
        BigDecimal grants,
        Integer    profnum,
        Integer    zachnum
    ) {
        this.studNum = studNum;
        this.fio = fio;
        this.grpnum = grpnum;
        this.grants = grants;
        this.profnum = profnum;
        this.zachnum = zachnum;
    }

    public Integer getStudNum() {
        return this.studNum;
    }

    public void setStudNum(Integer studNum) {
        this.studNum = studNum;
    }

    public String getFio() {
        return this.fio;
    }

    public void setFio(String fio) {
        this.fio = fio;
    }

    public Integer getGrpnum() {
        return this.grpnum;
    }

    public void setGrpnum(Integer grpnum) {
        this.grpnum = grpnum;
    }

    public BigDecimal getGrants() {
        return this.grants;
    }

    public void setGrants(BigDecimal grants) {
        this.grants = grants;
    }

    public Integer getProfnum() {
        return this.profnum;
    }

    public void setProfnum(Integer profnum) {
        this.profnum = profnum;
    }

    public Integer getZachnum() {
        return this.zachnum;
    }

    public void setZachnum(Integer zachnum) {
        this.zachnum = zachnum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(studNum);
        sb.append(", ").append(fio);
        sb.append(", ").append(grpnum);
        sb.append(", ").append(grants);
        sb.append(", ").append(profnum);
        sb.append(", ").append(zachnum);

        sb.append(")");
        return sb.toString();
    }
}
