/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.db;


import javax.annotation.Generated;

import ru.sevsu.db.db.tables.Student;


/**
 * Convenience access to all tables in db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>db.student</code>.
     */
    public static final Student STUDENT = ru.sevsu.db.db.tables.Student.STUDENT;
}
