/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.db;


import javax.annotation.Generated;

import ru.sevsu.db.db.tables.Course;
import ru.sevsu.db.db.tables.Exercise;
import ru.sevsu.db.db.tables.StudCourseLink;
import ru.sevsu.db.db.tables.Student;
import ru.sevsu.db.db.tables.Teacher;


/**
 * Convenience access to all tables in db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>db.course</code>.
     */
    public static final Course COURSE = ru.sevsu.db.db.tables.Course.COURSE;

    /**
     * The table <code>db.exercise</code>.
     */
    public static final Exercise EXERCISE = ru.sevsu.db.db.tables.Exercise.EXERCISE;

    /**
     * The table <code>db.stud_course_link</code>.
     */
    public static final StudCourseLink STUD_COURSE_LINK = ru.sevsu.db.db.tables.StudCourseLink.STUD_COURSE_LINK;

    /**
     * The table <code>db.student</code>.
     */
    public static final Student STUDENT = ru.sevsu.db.db.tables.Student.STUDENT;

    /**
     * The table <code>db.teacher</code>.
     */
    public static final Teacher TEACHER = ru.sevsu.db.db.tables.Teacher.TEACHER;
}
