/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MyCourses implements Serializable {

    private static final long serialVersionUID = 2084971316;

    private String fio;
    private String courseName;

    public MyCourses() {}

    public MyCourses(MyCourses value) {
        this.fio = value.fio;
        this.courseName = value.courseName;
    }

    public MyCourses(
        String fio,
        String courseName
    ) {
        this.fio = fio;
        this.courseName = courseName;
    }

    public String getFio() {
        return this.fio;
    }

    public void setFio(String fio) {
        this.fio = fio;
    }

    public String getCourseName() {
        return this.courseName;
    }

    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MyCourses (");

        sb.append(fio);
        sb.append(", ").append(courseName);

        sb.append(")");
        return sb.toString();
    }
}
