/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.public_.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Table implements Serializable {

    private static final long serialVersionUID = -1888867851;

    private Integer id;

    public Table() {}

    public Table(Table value) {
        this.id = value.id;
    }

    public Table(
        Integer id
    ) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Table (");

        sb.append(id);

        sb.append(")");
        return sb.toString();
    }
}
