/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import ru.sevsu.db.tables.Course;
import ru.sevsu.db.tables.Exercise;
import ru.sevsu.db.tables.StudCourseLink;
import ru.sevsu.db.tables.Student;
import ru.sevsu.db.tables.Teacher;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Db extends SchemaImpl {

    private static final long serialVersionUID = -564663926;

    /**
     * The reference instance of <code>db</code>
     */
    public static final Db DB = new Db();

    /**
     * The table <code>db.course</code>.
     */
    public final Course COURSE = ru.sevsu.db.tables.Course.COURSE;

    /**
     * The table <code>db.exercise</code>.
     */
    public final Exercise EXERCISE = ru.sevsu.db.tables.Exercise.EXERCISE;

    /**
     * The table <code>db.stud_course_link</code>.
     */
    public final StudCourseLink STUD_COURSE_LINK = ru.sevsu.db.tables.StudCourseLink.STUD_COURSE_LINK;

    /**
     * The table <code>db.student</code>.
     */
    public final Student STUDENT = ru.sevsu.db.tables.Student.STUDENT;

    /**
     * The table <code>db.teacher</code>.
     */
    public final Teacher TEACHER = ru.sevsu.db.tables.Teacher.TEACHER;

    /**
     * No further instances allowed
     */
    private Db() {
        super("db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.SEQ_GET_ID);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Course.COURSE,
            Exercise.EXERCISE,
            StudCourseLink.STUD_COURSE_LINK,
            Student.STUDENT,
            Teacher.TEACHER);
    }
}
