/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import ru.sevsu.db.tables.Course;
import ru.sevsu.db.tables.Exercise;
import ru.sevsu.db.tables.StudCourseLink;
import ru.sevsu.db.tables.Student;
import ru.sevsu.db.tables.Teacher;
import ru.sevsu.db.tables.records.CourseRecord;
import ru.sevsu.db.tables.records.ExerciseRecord;
import ru.sevsu.db.tables.records.StudCourseLinkRecord;
import ru.sevsu.db.tables.records.StudentRecord;
import ru.sevsu.db.tables.records.TeacherRecord;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>db</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CourseRecord> COURSE_PKEY = UniqueKeys0.COURSE_PKEY;
    public static final UniqueKey<ExerciseRecord> EXERCISE_PKEY = UniqueKeys0.EXERCISE_PKEY;
    public static final UniqueKey<StudCourseLinkRecord> STUD_COURSE_LINK_PKEY = UniqueKeys0.STUD_COURSE_LINK_PKEY;
    public static final UniqueKey<StudentRecord> STUDENT_PKEY = UniqueKeys0.STUDENT_PKEY;
    public static final UniqueKey<StudentRecord> STUDENT_ZACHNUM_KEY = UniqueKeys0.STUDENT_ZACHNUM_KEY;
    public static final UniqueKey<TeacherRecord> TEACHER_PKEY = UniqueKeys0.TEACHER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CourseRecord, TeacherRecord> COURSE__FK__COURSE_TEACHER_NUM__TEACHER_TEACHER_NUM = ForeignKeys0.COURSE__FK__COURSE_TEACHER_NUM__TEACHER_TEACHER_NUM;
    public static final ForeignKey<ExerciseRecord, CourseRecord> EXERCISE__FK__EXERCISE_COURSE_NUM__COURSE_COURSE_NUM = ForeignKeys0.EXERCISE__FK__EXERCISE_COURSE_NUM__COURSE_COURSE_NUM;
    public static final ForeignKey<StudCourseLinkRecord, StudentRecord> STUD_COURSE_LINK__FK__STUD_COURSE_LINK_STUD_NUM__STUDENT_STUD_NUM = ForeignKeys0.STUD_COURSE_LINK__FK__STUD_COURSE_LINK_STUD_NUM__STUDENT_STUD_NUM;
    public static final ForeignKey<StudCourseLinkRecord, CourseRecord> STUD_COURSE_LINK__FK__STUD_COURSE_LINK_COURSE_NUM__COURSE_COURSE_NUM = ForeignKeys0.STUD_COURSE_LINK__FK__STUD_COURSE_LINK_COURSE_NUM__COURSE_COURSE_NUM;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CourseRecord> COURSE_PKEY = Internal.createUniqueKey(Course.COURSE, "course_pkey", Course.COURSE.COURSE_NUM);
        public static final UniqueKey<ExerciseRecord> EXERCISE_PKEY = Internal.createUniqueKey(Exercise.EXERCISE, "exercise_pkey", Exercise.EXERCISE.EX_ID);
        public static final UniqueKey<StudCourseLinkRecord> STUD_COURSE_LINK_PKEY = Internal.createUniqueKey(StudCourseLink.STUD_COURSE_LINK, "stud_course_link_pkey", StudCourseLink.STUD_COURSE_LINK.SCL_ID);
        public static final UniqueKey<StudentRecord> STUDENT_PKEY = Internal.createUniqueKey(Student.STUDENT, "student_pkey", Student.STUDENT.STUD_NUM);
        public static final UniqueKey<StudentRecord> STUDENT_ZACHNUM_KEY = Internal.createUniqueKey(Student.STUDENT, "student_zachnum_key", Student.STUDENT.ZACHNUM);
        public static final UniqueKey<TeacherRecord> TEACHER_PKEY = Internal.createUniqueKey(Teacher.TEACHER, "teacher_pkey", Teacher.TEACHER.TEACHER_NUM);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CourseRecord, TeacherRecord> COURSE__FK__COURSE_TEACHER_NUM__TEACHER_TEACHER_NUM = Internal.createForeignKey(ru.sevsu.db.Keys.TEACHER_PKEY, Course.COURSE, "course__fk__course_teacher_num__teacher_teacher_num", Course.COURSE.TEACHER_NUM);
        public static final ForeignKey<ExerciseRecord, CourseRecord> EXERCISE__FK__EXERCISE_COURSE_NUM__COURSE_COURSE_NUM = Internal.createForeignKey(ru.sevsu.db.Keys.COURSE_PKEY, Exercise.EXERCISE, "exercise__fk__exercise_course_num__course_course_num", Exercise.EXERCISE.COURSE_NUM);
        public static final ForeignKey<StudCourseLinkRecord, StudentRecord> STUD_COURSE_LINK__FK__STUD_COURSE_LINK_STUD_NUM__STUDENT_STUD_NUM = Internal.createForeignKey(ru.sevsu.db.Keys.STUDENT_PKEY, StudCourseLink.STUD_COURSE_LINK, "stud_course_link__fk__stud_course_link_stud_num__student_stud_num", StudCourseLink.STUD_COURSE_LINK.STUD_NUM);
        public static final ForeignKey<StudCourseLinkRecord, CourseRecord> STUD_COURSE_LINK__FK__STUD_COURSE_LINK_COURSE_NUM__COURSE_COURSE_NUM = Internal.createForeignKey(ru.sevsu.db.Keys.COURSE_PKEY, StudCourseLink.STUD_COURSE_LINK, "stud_course_link__fk__stud_course_link_course_num__course_course_num", StudCourseLink.STUD_COURSE_LINK.COURSE_NUM);
    }
}
