/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>db.seq_get_id</code>
     */
    public static final Sequence<Long> SEQ_GET_ID = new SequenceImpl<Long>("seq_get_id", Db.DB, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
