/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import ru.sevsu.db.Db;
import ru.sevsu.db.Indexes;
import ru.sevsu.db.Keys;
import ru.sevsu.db.tables.records.StudCourseLinkRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudCourseLink extends TableImpl<StudCourseLinkRecord> {

    private static final long serialVersionUID = -2043001134;

    /**
     * The reference instance of <code>db.stud_course_link</code>
     */
    public static final StudCourseLink STUD_COURSE_LINK = new StudCourseLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudCourseLinkRecord> getRecordType() {
        return StudCourseLinkRecord.class;
    }

    /**
     * The column <code>db.stud_course_link.scl_id</code>.
     */
    public final TableField<StudCourseLinkRecord, Integer> SCL_ID = createField("scl_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>db.stud_course_link.stud_num</code>.
     */
    public final TableField<StudCourseLinkRecord, Integer> STUD_NUM = createField("stud_num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>db.stud_course_link.course_num</code>.
     */
    public final TableField<StudCourseLinkRecord, Integer> COURSE_NUM = createField("course_num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>db.stud_course_link</code> table reference
     */
    public StudCourseLink() {
        this(DSL.name("stud_course_link"), null);
    }

    /**
     * Create an aliased <code>db.stud_course_link</code> table reference
     */
    public StudCourseLink(String alias) {
        this(DSL.name(alias), STUD_COURSE_LINK);
    }

    /**
     * Create an aliased <code>db.stud_course_link</code> table reference
     */
    public StudCourseLink(Name alias) {
        this(alias, STUD_COURSE_LINK);
    }

    private StudCourseLink(Name alias, Table<StudCourseLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private StudCourseLink(Name alias, Table<StudCourseLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> StudCourseLink(Table<O> child, ForeignKey<O, StudCourseLinkRecord> key) {
        super(child, key, STUD_COURSE_LINK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Db.DB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STUD_COURSE_LINK_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StudCourseLinkRecord> getPrimaryKey() {
        return Keys.STUD_COURSE_LINK_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StudCourseLinkRecord>> getKeys() {
        return Arrays.<UniqueKey<StudCourseLinkRecord>>asList(Keys.STUD_COURSE_LINK_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StudCourseLinkRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StudCourseLinkRecord, ?>>asList(Keys.STUD_COURSE_LINK__FK__STUD_COURSE_LINK_STUD_NUM__STUDENT_STUD_NUM, Keys.STUD_COURSE_LINK__FK__STUD_COURSE_LINK_COURSE_NUM__COURSE_COURSE_NUM);
    }

    public Student student() {
        return new Student(this, Keys.STUD_COURSE_LINK__FK__STUD_COURSE_LINK_STUD_NUM__STUDENT_STUD_NUM);
    }

    public Course course() {
        return new Course(this, Keys.STUD_COURSE_LINK__FK__STUD_COURSE_LINK_COURSE_NUM__COURSE_COURSE_NUM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudCourseLink as(String alias) {
        return new StudCourseLink(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudCourseLink as(Name alias) {
        return new StudCourseLink(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StudCourseLink rename(String name) {
        return new StudCourseLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StudCourseLink rename(Name name) {
        return new StudCourseLink(name, null);
    }
}
