/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.public_.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.sevsu.db.public_.tables.MyCourses;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MyCoursesRecord extends TableRecordImpl<MyCoursesRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1319615093;

    /**
     * Setter for <code>public.my_courses.fio</code>.
     */
    public void setFio(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.my_courses.fio</code>.
     */
    public String getFio() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.my_courses.course_name</code>.
     */
    public void setCourseName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.my_courses.course_name</code>.
     */
    public String getCourseName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MyCourses.MY_COURSES.FIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MyCourses.MY_COURSES.COURSE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getFio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCourseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCourseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyCoursesRecord value1(String value) {
        setFio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyCoursesRecord value2(String value) {
        setCourseName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MyCoursesRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MyCoursesRecord
     */
    public MyCoursesRecord() {
        super(MyCourses.MY_COURSES);
    }

    /**
     * Create a detached, initialised MyCoursesRecord
     */
    public MyCoursesRecord(String fio, String courseName) {
        super(MyCourses.MY_COURSES);

        set(0, fio);
        set(1, courseName);
    }
}
