/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import ru.sevsu.db.db.tables.Course;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CourseRecord extends UpdatableRecordImpl<CourseRecord> implements Record5<Integer, Integer, String, String, String> {

    private static final long serialVersionUID = 1458590461;

    /**
     * Setter for <code>db.course.course_num</code>.
     */
    public void setCourseNum(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.course.course_num</code>.
     */
    public Integer getCourseNum() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db.course.teacher_num</code>.
     */
    public void setTeacherNum(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.course.teacher_num</code>.
     */
    public Integer getTeacherNum() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db.course.course_name</code>.
     */
    public void setCourseName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.course.course_name</code>.
     */
    public String getCourseName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db.course.course_description</code>.
     */
    public void setCourseDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.course.course_description</code>.
     */
    public String getCourseDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db.course.tmp_course_name</code>.
     */
    public void setTmpCourseName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db.course.tmp_course_name</code>.
     */
    public String getTmpCourseName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Course.COURSE.COURSE_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Course.COURSE.TEACHER_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Course.COURSE.COURSE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Course.COURSE.COURSE_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Course.COURSE.TMP_COURSE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCourseNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getTeacherNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCourseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCourseDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getTmpCourseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCourseNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTeacherNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCourseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCourseDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTmpCourseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value1(Integer value) {
        setCourseNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value2(Integer value) {
        setTeacherNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value3(String value) {
        setCourseName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value4(String value) {
        setCourseDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord value5(String value) {
        setTmpCourseName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CourseRecord values(Integer value1, Integer value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourseRecord
     */
    public CourseRecord() {
        super(Course.COURSE);
    }

    /**
     * Create a detached, initialised CourseRecord
     */
    public CourseRecord(Integer courseNum, Integer teacherNum, String courseName, String courseDescription, String tmpCourseName) {
        super(Course.COURSE);

        set(0, courseNum);
        set(1, teacherNum);
        set(2, courseName);
        set(3, courseDescription);
        set(4, tmpCourseName);
    }
}
