/*
 * This file is generated by jOOQ.
 */
package ru.sevsu.db.db.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import ru.sevsu.db.db.tables.Student;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends TableRecordImpl<StudentRecord> implements Record5<Long, String, Short, BigDecimal, Integer> {

    private static final long serialVersionUID = 384070689;

    /**
     * Setter for <code>db.student.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>db.student.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>db.student.fio</code>.
     */
    public void setFio(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db.student.fio</code>.
     */
    public String getFio() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db.student.grp_num</code>.
     */
    public void setGrpNum(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>db.student.grp_num</code>.
     */
    public Short getGrpNum() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>db.student.grants</code>.
     */
    public void setGrants(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>db.student.grants</code>.
     */
    public BigDecimal getGrants() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>db.student.prof_num</code>.
     */
    public void setProfNum(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>db.student.prof_num</code>.
     */
    public Integer getProfNum() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Short, BigDecimal, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, Short, BigDecimal, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Student.STUDENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Student.STUDENT.FIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field3() {
        return Student.STUDENT.GRP_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Student.STUDENT.GRANTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Student.STUDENT.PROF_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component3() {
        return getGrpNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getGrants();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getProfNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value3() {
        return getGrpNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getGrants();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getProfNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value2(String value) {
        setFio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value3(Short value) {
        setGrpNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value4(BigDecimal value) {
        setGrants(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value5(Integer value) {
        setProfNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord values(Long value1, String value2, Short value3, BigDecimal value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Long id, String fio, Short grpNum, BigDecimal grants, Integer profNum) {
        super(Student.STUDENT);

        set(0, id);
        set(1, fio);
        set(2, grpNum);
        set(3, grants);
        set(4, profNum);
    }
}
